apiVersion: v1
kind: Pod
metadata:
  name: nginx-sidecar
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: log-volume
    - name: sidecar
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /var/log/nginx-sidecar
          name: log-volume
  volumes:
    - name: log-volume
      emptyDir: {}